config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  get 'gallery/index', to: 'gallery#index'
  get 'blogs', to: 'blogs#index'
  get 'blogs/new', to: 'blogs#new'
  post 'blogs', to:'blogs#create'
  post 'blogs', to: 'blogs#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/gallery.rb
class Gallery < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blogs = Blog.all
  end

  def create
    Blog.create(blog_params)

  end

  private
  def blog_params
    params.permit(:date,:title,:content)
  end

end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/create.html.erb
<h1>投稿が完了しました</h1>
<%= link_to 'トップページに戻る', '/blogs' %>

app/views/blogs/index.html.erb
<div class="main-title">ブログ</div>

<%= link_to '新規投稿', '/blogs/new' %>
  
<% @blogs.each do |blog| %>
  <div class="blog">
    <div class="blog-date">
      投稿日時：<%= blog.date %>
    </div>
    <div class="blog-title">
      タイトル:<%= blog.title %>
    </div>
    <div class="blog-content">
      <%= blog.content %>
    </div>
  </div>
<% end %>

app/views/blogs/new.html.erb
<h1>新規投稿ページ</h1>

<%= form_tag('/blogs', method: :post) do %> 
      <p>投稿日時<input type="date" name="date" class="date"> </p>
   　　  <p><textarea name="title" cols="30" rows="1"></textarea></p>
   <textarea name="content" cols="30" rows="5"></textarea>
  　　 <p><input type="submit" value="投稿する"></p>

<% end %>

app/views/gallery/index.html.haml
.gallery

  .gallery_header
    ギャラリー一覧
  .gallery_main
    .gallery_main2
      = image_tag "IMG_0324.JPG", :size =>'250x200'
      = image_tag "https://publicdomainq.net/images/201710/07s/publicdomainq-0014143ddc.jpg", :size=> '250x200'
      = image_tag "https://www.pakutaso.com/shared/img/thumb/KAZUHIRO171013022_TP_V.jpg", :size =>'250x200'

  .gallery_bottom
    = link_to("戻る",root_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title APP1
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/_form.html.haml
.form
  -# = form_for [@post] do |f|
  -#   = f.text_field :content, class: 'form__message', placeholder: 'type a message'
  -#   .form__mask
  -#     = f.label :image, class: 'form__mask__image' do
  -#       = icon('fas', 'image', class: 'icon')
  -#       = f.file_field :image, class: 'hidden'
  -#   = f.submit 'Send', class: 'form__submit'
      
  

app/views/posts/_header.html.haml
.header
  %h2.header_name
    Hair-Olive
.nabi
  %ul.nabi_bar_list
    %li.nabi_bar_list
      =link_to("Menu",root_path)
    %li.nabi_bar_list
      =link_to("スタッフ一覧",root_path)
    %li.nabi_bar_list
      =link_to("ギャラリー",gallery_index_path)
    %li.nabi_bar_list
      =link_to("アクセス",root_path)
    %li.nabi_bar_list
      =link_to("ブログ",blogs_path)
    %li.nabi_bar_list
      =link_to("レビュー",root_path)

app/views/posts/_info.html.haml
.info
  .left  
    .infomation
      【infomation】
    .table
      .date
        2019/12/31
      .title
        【新着情報】
      .title2
        クーポン使用できます
    .table
      .date
        2020/01/05
      .title
        【ブログUP情報】
      .title2
        今日から〜〜〜
  .right
    .right-box
    
    

app/views/posts/index.html.haml
.wrapper
  = render "header"
  = render "info"
  = render "form"
  -# = render "footer"